### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by haggertyg** [Pyhass/Hive-Custom-Component#101]
In the latest version of the Hive integration, updated via HACS, the integration will no longer load.

I cant see how / where to check credentials as the setup also no longer appears

running under HA in a docker container

**Screenshots**
Logger: homeassistant.setup
Source: setup.py:164
First occurred: 14:53:10 (1 occurrences)
Last logged: 14:53:10

Setup failed for hive: Unable to import component: cannot import name 'ConfigEntryAuthFailed' from 'homeassistant.exceptions' (/usr/src/homeassistant/homeassistant/exceptions.py)

**Comment by haggertyg** [comment]
Just an update. I removed this component and went back to the standard integration and it started working again (less entities though). I tries reinstalling again today and I have exactly the same issue again

**Comment by jamesmheath** [comment]
I had the same issue. Deleted and added the integration again. I now have the sensor entities back but the climate enitiy is missing. So I can monitor the heating but not control it

**Comment by jmoorey1** [comment]
Getting exactly the same error.

Running Home Assistant core-2021.4.1.

![image](https://user-images.githubusercontent.com/63410949/120152157-0c1f9500-c1e5-11eb-8f68-34d1678f1b4f.jpeg)
![image](https://user-images.githubusercontent.com/63410949/120152191-18a3ed80-c1e5-11eb-9894-e8a9609e7070.jpeg)

**Comment by jmoorey1** [comment]
> Getting exactly the same error.
> 
> Running Home Assistant core-2021.4.1.
> 
> ![image](https://user-images.githubusercontent.com/63410949/120152157-0c1f9500-c1e5-11eb-8f68-34d1678f1b4f.jpeg)
> ![image](https://user-images.githubusercontent.com/63410949/120152191-18a3ed80-c1e5-11eb-9894-e8a9609e7070.jpeg)

Had to update Home Assistant to **2021.5.5**. There were some new exceptions added that this new version takes advantage of.

Deleted the integration, reinstalled from HACS. Then after a clean bounce added Hive again, asked for a fresh auth and works a treat.
