### ISSUE TITLE
Integration not showing in HACS

### ISSUE THREAD

**Issue by mikebakke** [Pyhass/Hive-Custom-Component#103]
Instakked HACS on a Pi docker container and when I search for new integrations in HACS there is no sign of Hive.

**To Reproduce**
Click on HACS / Click on add integrations / Search for hive

**Expected behaviour**
Hive custom integration offered to install

**Screenshots**

**Desktop (please complete the following information):**

- HACS version 1.12.4
- HASS version 2021-5.5
![hive2](https://user-images.githubusercontent.com/55141164/120346989-cb627180-c2f3-11eb-9216-aad42b4605f0.png)

**Comment by mikebakke** [comment]
For whatever reason - it has now appeared and installed. Sigh. 

I can only think it was because I had a crash on my host and did a full restart of everything to get all my dockers back.

**Comment by KJonline** [comment]
If you just installed HACs it can take some time for the HACs to initialise and download the available components
