### ISSUE TITLE
[FEATURE] Support for Hive Siren & Keypad

### ISSUE THREAD

**Issue by RichardMawdsley** [Pyhass/Hive-Custom-Component#106]
**Is your feature request related to a problem? 
No

**Describe the solution you'd like**
Hive have released two new products, a Siren & Keypad.  I'd like support for both of these in HA.
** In fairness, I'm basing my assumption that these are not currently supported by way of lack of documentation for them, I don't currently own them, so am unable to be sure.

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.hivehome.com/shop/smart-home-security/hive-siren
https://www.hivehome.com/shop/smart-home-security/hive-keypad

**Comment by KJonline** [comment]
There is an open pull request for this already which is waiting to be reviewed by the home assistant team.

**Comment by RichardMawdsley** [comment]
Any update on this @KJonline?

**Comment by Azeem-Sultan** [comment]
Does this now work?

**Comment by dougle03** [comment]
> Does this now work?

Works fine for me.

**Comment by KJonline** [comment]
Ye the home assistant team have reviewed and this is now in the home assistant base code

**Comment by dougle03** [comment]
> now in the home assistant base code

does this mean the core integration for Hive is now yours? If so, does this mean I can remove the custom component version?
