### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by damo9999** [Pyhass/Hive-Custom-Component#112]
When I enable the integration it initially works and pulls in the devices/entities and their values but after an hour or two it stops updating. At the same time it also seems to block my ability to log into the Hive App or Website.

I cannot see any clear indication in the logs what is happening.

Using Home Assistant Operating System on RPI 3b (but same problem occurred using it in a VM on my PC).

I had previously been using Domoticz and it's plugin wont login at all.

**Comment by cpdowsett** [comment]
Glad I just found this as I have the exact same thing issue on my system. Found I could only log in from a cell connection and not WiFi. Also the boat commands to do my hot water stopped.

**Comment by mjburton** [comment]
I had the same as @cpdowsett - though I can now login via a web browser on home internet connection. 2FA code entered after HA restart, values pulled but then they stop refreshing/connecting. Seems to be the token expired issue on other threads.

**Comment by KJonline** [comment]
This is fixed in the latest version
