### ISSUE TITLE
[BUG] Heating Availability change to Online every 15sec in logbook

### ISSUE THREAD

**Issue by geftactics** [Pyhass/Hive-Custom-Component#114]
**Describe the bug**
Home Assistant 2022.6.5 / Hive integration 2021.5.4
Logbook shows 'Heating Availability change to Online' every 15 seconds.
these entries do not persist in the log (i.e vanish on page refresh, but then start appearing again)

**To Reproduce**
Steps to reproduce the behaviour:

1. Logbook
2. Wait 15 seconds or more
3. See issue

**Expected behaviour**
Only see this item in the logbook if the status has changed.

**Additional context**
Visible in companion app, and also latest Chrome browser on macOS

**Comment by KJonline** [comment]
please update to the latest version and re-test I have checked In 2022.7.1 and im not seeing this issue
