### ISSUE TITLE
Device status change taking ages in Home Assistant

### ISSUE THREAD

**Issue by Johnyb62** [Pyhass/Hive-Custom-Component#118]
Background:
Upgraded from 2021.5.4 > 2022.6.1
With the previous version I didn't have 2FA enabled, so to upgrade I removed the integration - enabled 2FA in Hive App, re-added integration & configured - devices now working

Issue:-
When changing the state of a device (eg light off > on) whilst the device itself responds immediately - the state in HA doesn't change to reflect that change for a few minutes.   Example:  Turn On light in HA.  Light itself immediately turns on, however the state of the light in HA remains showing off.  After a couple of minutes the status 'catches up' and changes to On.  

**Expected behaviour**
Prior to upgrading to the latest version (which required me to enable 2FA), the state change would be immediately reflected in HA.
Meaning the correct device state was shown.  Therefore allowing me to immediately change its state again (if required)
 
Running Home Assistant Core 2022.6.7

**Comment by Johnyb62** [comment]
Note: Disabling 2FA in the Hive App, and rolling back to the previously installed version 2021.5.4 resolved the issue.

**Comment by KJonline** [comment]
This should be fixed in the new release

**Comment by Johnyb62** [comment]
Working just fine now.  Thank you
