### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MKTestAccount100** [Pyhass/Hive-Custom-Component#121]
**Describe the bug**
I have recently started getting issues with HACS-Hive custom integration. I removed and readded the integration. Once I try to enter my credentials, I get 'Unknown error occurred'

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Settings >> Devices and Services
2. Add new integration
3. Search and try to add hive
4. enter credentials

**Expected behaviour**
I expected it to accept the credetnials and add all required entities. 

** Other Information **
Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.07.0
HACS 1.25.5
Hive Custom Component 2022.7.1

**Comment by KJonline** [comment]
You need to be on Home Assistant Core 2022.7.0 for hive custom component 2022.7.1 to work. Please  upgrade to the latest version of home assistant core and retry. If it’s still an issue please raise a separate bug.
