### ISSUE TITLE
[BUG] Error adding entities for domain water_heater with platform hive

### ISSUE THREAD

**Issue by sym0nd0** [Pyhass/Hive-Custom-Component#122]
**Describe the bug**
Following update to HA 2022.7.2, I've started seeing the following in my logs:
```
Logger: homeassistant.components.water_heater
Source: custom_components/hive/water_heater.py:78
Integration: Water Heater (documentation, issues)
First occurred: 09:05:32 (2 occurrences)
Last logged: 09:05:32

Error adding entities for domain water_heater with platform hive
Error while setting up hive platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 457, in _async_add_entity
    if entity.unique_id is not None:
  File "/config/custom_components/hive/water_heater.py", line 78, in unique_id
    return self._unique_id
AttributeError: 'HiveWaterHeater' object has no attribute '_unique_id'
```
As a result the entity for Hot Water is unavailable.

**To Reproduce**
Steps to reproduce the behaviour:

1. Update HA to 2022.7.2

**Expected behaviour**
Available Hot Water entity, controllable through HA

**Screenshots**
![image](https://user-images.githubusercontent.com/55590428/178097947-e36869b8-42ab-46e1-844a-23b8704550ad.png)

**Desktop (please complete the following information):**

- OS: Windows 11 Home (build 22000.739)
- Browser Microsoft Edge
- Version 103.0.1264.49 (Official build) (64-bit)

**Additional context**
Home Assistant 2022.7.2
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0 - latest

Hive Custom Component 2022.7.1

**Comment by daanvb** [comment]
I'm also seeing this too

**Comment by holdestmade** [comment]
Me too

**Comment by virtusas** [comment]
Same here. No Hot Water Entity available.

**Comment by KJonline** [comment]
Please can this be retested 2022.7.2 has been released to address this

**Comment by virtusas** [comment]
I am on core 2022.7.3 and still same. Added in as new from scratch and same result.

**Comment by holdestmade** [comment]
Worked for me, water heater in now working fine

HA2022.7.3

**Comment by virtusas** [comment]
Did you remove 

> Worked for me, water heater in now working fine
> 
> HA2022.7.3

What steps did you take to fix it, or you just left it to update to 2022.7.3? 
As I removed it on 2022.7.2, added in again and no help. Now Im on 2022.7.3 and same. I wonder should I remove repository from HACS and add as brand new?
Thank you.

**Comment by holdestmade** [comment]
I just clicked on update in HACS and restarted

**Comment by sym0nd0** [comment]
> Please can this be retested 2022.7.2 has been released to address this

No change for me on 2022.7.3. If you need any more logs or data give me a shout.

**Comment by KJonline** [comment]
@virtusas have you upgraded trough hacs to hive custom component version 2022.7.2

**Comment by virtusas** [comment]
> @virtusas have you upgraded trough hacs to hive custom component version 2022.7.2

Yep. Just now updated, restarted and same :(

**Comment by virtusas** [comment]
> @virtusas have you upgraded trough hacs to hive custom component version 2022.7.2

Back in action. Deleted again, redownloaded repository installed as normal. And came back now. 
Thank you kindly.

**Comment by KJonline** [comment]
Closing this as the issue seems to be fixed
