### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by perjury** [Pyhass/Hive-Custom-Component#126]
**Describe the bug**
Hive plugs unit power unit of measurement is showing as kW and should be W (as per https://github.com/home-assistant/core/pull/75210 )

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Developer Tools>States and filter on any Hive pug
4. It displays 'unit_of_measurement: kW'

**Expected behaviour**
 It displays 'unit_of_measurement: W'

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by perjury** [comment]
Running core-2022.7.7

**Comment by perjury** [comment]
![Developer-Tools-–-Home-Assistant](https://user-images.githubusercontent.com/11613248/182015580-cad47c75-2ba5-4c95-8f57-5ad4a58a8180.png)

**Comment by KJonline** [comment]
@perjury i can you let me know if this is fixed in the latest release I believe a fix was done for this. Ill reopen if it’s still an issue

**Comment by perjury** [comment]
Yes, appears to be fixed. Thanks for your efforts
