### ISSUE TITLE
[BUG] Boost hot water service doesn't work

### ISSUE THREAD

**Issue by cstosgale** [Pyhass/Hive-Custom-Component#127]
**Describe the bug**
When I call the service hive.boost_hot_water nothing happens. Nothing is logged in the HA logs and the hot water doesn't get boosted.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Developer tools -> Services
2. Submit the following YAML (replacing main_house with the name of your hive water heater entity:

service: hive.boost_hot_water
data:
  entity_id: water_heater.main_house
  time_period: "00:00:30"
  on_off: "on"

3. Click call service.
4. Confirm hot water is not boosted in hive

**Expected behaviour**
Hot water should be boosted when this service is run

Home assistant version: 2022.9.1

**Comment by KJonline** [comment]
@cstosgale are there any errors in the logs when this occurs?

**Comment by cstosgale** [comment]
No, nothing in the main Home Assistant log, is there anywhere else I should be looking?

**Comment by KJonline** [comment]
No, problem I have is I don’t actually have hot water.

I developed all by using other peoples data who they shared with me and then sent them beta builds to test with. 

Does the hotwater boost work in the home-assistant core version, so not the custom component.

**Comment by dougle03** [comment]
@KJonline @cstosgale 
Morning all. Just tried the yaml in the OP post and also didn't work. Then tried 30mins instead of 30secs and it works.
Perhaps 30seconds is too short and hive ignores it.
![image](https://user-images.githubusercontent.com/59865048/190849531-0e288d47-8035-444a-ae89-aa82a6a2a56c.png)

**Comment by dougle03** [comment]
Running 2022.9.4
![image](https://user-images.githubusercontent.com/59865048/190849600-ec1a8a8e-cf92-4cfd-8471-1bdc6076fc8e.png)

**Comment by cstosgale** [comment]
Many thanks, I am a total fool, I thought I was setting it for 30 minutes, not 30 seconds! 

That makes perfect sense, no one would reasonably want to boost their heating for 30 seconds so no wonder it doesn't work.

For reference, I confirmed this integration just imports the water heater python code from the official Hive integration, so the bug couldn't have been in this integration anyway.
