### ISSUE TITLE
[BUG] "Boost ends in" attribute missing

### ISSUE THREAD

**Issue by CaptInsano** [Pyhass/Hive-Custom-Component#128]
With the heating starting to go back on in my house I noticed a bug since before the summer.

The attribute "Boost ends in" is no longer present for the boost entities:

![image](https://user-images.githubusercontent.com/332478/192162489-35134d86-fc23-4732-beaa-a5b3c46c01dd.png)

As you can see I use a conditional card to show remaining boost time if a zone is boosted but now it reports "unknown".

Is it possible to get this attribure re-added or is there an otehr solution?

**Comment by Doghousestaffs** [comment]
+1, I also have the same issue..really frustrating, the attribute is supposed to be part of the sensor.home_boost but it’s no longer there

**Comment by CaptInsano** [comment]
Fixed in 2022.10.0

Thanks so much dev
