### ISSUE TITLE
Hive component fails if using Hive Camera but no recordings available[BUG]

### ISSUE THREAD

**Issue by perjury** [Pyhass/Hive-Custom-Component#129]
**Describe the bug**
If there is no recording available for an installed Hive camera, the Hive integration stops working.
If you try to install it, the installation fails
If it is installed and then one of the cameras no longer has any recordings available, it stops updating HA

**To Reproduce**
Install Hive Camera
Don't have any camera recordings available for that camera

**Expected behaviour**
Everything should work as normally

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
See this discussion https://community.home-assistant.io/t/hive-integration-error-in-2022-7/439735/11?u=perjury1 .

**Comment by KJonline** [comment]
This was fixed in the latest release
