### ISSUE TITLE
Ability to enable/disable Heat On Demand (HoD) from HA

### ISSUE THREAD

**Issue by sym0nd0** [Pyhass/Hive-Custom-Component#72]
**Is your feature request related to a problem? Please describe.**
As HoD boosts any open radiator, when a TRV is calling for heat, those rooms can get sweltering - as you have to typically have HoD set to a much higher temp to allow it to function as designed.

**Describe the solution you'd like**
If it's possible, I'd like to be able to control HoD from HA, with the plan to automate enabling HoD during certain hours and disabling it during other periods, i.e. HoD on between 08:00-16:00 but off at all other times, stopping the bedroom hitting 25° C during the night whilst the heating system tries to keep the bathroom at 21° C.

**Describe alternatives you've considered**
Manually adjusting HoD through the Hive app.

**Additional context**
![tempFileForShare_20210310-153127](https://user-images.githubusercontent.com/55590428/110661560-99da7e00-81bc-11eb-82ca-aab99f18455b.jpg)

Happy to test or supply any info/data, if required.

**Comment by KJonline** [comment]
This is included in home assistant 2021.5.0

**Comment by sym0nd0** [comment]
Thank you!
