### ISSUE TITLE
[BUG] Updating to 2021.4.0 failure

### ISSUE THREAD

**Issue by duartecordeiro** [Pyhass/Hive-Custom-Component#82]
After updating to latest release, can't get hive to work, even going back to older releases.
Just tried to start over from scratch, but still complaining.

- Removed Hive integration
- Removed Hive custom from HACS
- Restarted HA
- Installed 2021.4.0 inside HACS
- Restarted HA
- Cleared browser cache
- Tried to add the Hive integration
- Log show the following error:

    `Logger: homeassistant.config_entries
    Source: config_entries.py:546
    First occurred: 14:03:25 (3 occurrences)
    Last logged: 14:06:23
    
    Error occurred loading configuration flow for integration hive: cannot import name 'Pyhiveapi' from 'pyhiveapi' (/srv/homeassistant/lib/python3.8/site-packages/pyhiveapi/__init__.py)`

![Capture](https://user-images.githubusercontent.com/1743091/114305362-bde8f200-9acf-11eb-9572-bb10826b838f.PNG)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome
- Version 89.0.4389.114 (Official Build) (64-bit)

**Additional context**
## System Health

version | core-2021.2.1
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
virtualenv | true
python_version | 3.8.5
os_name | Linux
os_version | 5.4.0-66-generic
arch | x86_64
timezone | Europe/London

**Comment by KJonline** [comment]
Please can you check what version of this pyhiveapi you are running?

**Comment by duartecordeiro** [comment]
Hi, 
(homeassistant) homeassistant@store:/srv/homeassistant$ python3 -m pip list | grep hive
pyhiveapi               0.3.13

**Comment by duartecordeiro** [comment]
I've upgraded to 0.4.1, restarted HA and now the error is:

Logger: homeassistant.config_entries
Source: config_entries.py:546
First occurred: 18:46:17 (1 occurrences)
Last logged: 18:46:17

Error occurred loading configuration flow for integration hive: cannot import name 'Pyhiveapi' from 'pyhiveapi' (/srv/homeassistant/lib/python3.8/site-packages/pyhiveapi/__init__.py)

**Comment by duartecordeiro** [comment]
though about uninstalling everything again and reinstall... but ends up the same way:
pyhiveapi 0.3.13, same error in log file (cannot import name 'Pyhiveapi' from 'pyhiveapi')

**Comment by KJonline** [comment]
What command are you using to install pyhiveapi?

**Comment by duartecordeiro** [comment]
I don't do anything manually. I just install hive custom inside HACS and automatically get 0.3.13.
To upgrade, I did a manual:
 python3 -m pip install pyhiveapi -U 
inside the homesassistant env

**Comment by KJonline** [comment]
Would it be possible to find the pyhiveapi library in your virtual environment. And let me know what the contents of __init__.py 

there maybe 2 folders one called apyhiveapi and another called pyhiveapi please can you let me know what’s in both and if even if you have both.

**Comment by duartecordeiro** [comment]
Have both of them inside /srv/homeassistant/lib/python3.8/site-packages$

`(homeassistant) homeassistant@store:/srv/homeassistant/lib/python3.8/site-packages$ cat apyhiveapi/__init__.py
"""__init__.py."""
if __name__ == "pyhiveapi":
    from .api.hive_api import HiveApi as API  # noqa: F401
    from .api.hive_auth import HiveAuth as Auth  # noqa: F401
else:
    from .api.hive_async_api import HiveApiAsync as API  # noqa: F401
    from .api.hive_auth_async import HiveAuthAsync as Auth  # noqa: F401

from .helper.const import SMS_REQUIRED  # noqa: F401
from .hive import Hive  # noqa: F401
`

`(homeassistant) homeassistant@store:/srv/homeassistant/lib/python3.8/site-packages$ cat pyhiveapi/__init__.py
"""__init__.py."""
if __name__ == "pyhiveapi":
    from .api.hive_api import HiveApi as API  # noqa: F401
    from .api.hive_auth import HiveAuth as Auth  # noqa: F401
else:
    from .api.hive_async_api import HiveApiAsync as API  # noqa: F401
    from .api.hive_auth_async import HiveAuthAsync as Auth  # noqa: F401

from .helper.const import SMS_REQUIRED  # noqa: F401
from .hive import Hive  # noqa: F401
`

Thank you for your time helping

**Comment by KJonline** [comment]
Sorry yes, it’s 0.3.13 you need. 0.4.1 isn’t compatible with home assistant yet or the latest version of the custom component.

**Comment by duartecordeiro** [comment]
pyhiveapi 0.3.13

> cat apyhiveapi/__init__.py
"""__init__.py."""
if __name__ == "pyhiveapi":
    from .api.hive_api import HiveApi as API  # noqa: F401
    from .api.hive_auth import HiveAuth as Auth  # noqa: F401
else:
    from .api.hive_async_api import HiveApiAsync as API  # noqa: F401
    from .api.hive_auth_async import HiveAuthAsync as Auth  # noqa: F401
from .helper.const import SMS_REQUIRED  # noqa: F401
from .hive import Hive  # noqa: F401

> cat pyhiveapi/__init__.py
"""__init__.py."""
if __name__ == "pyhiveapi":
    from .api.hive_api import HiveApi as API  # noqa: F401
    from .api.hive_auth import HiveAuth as Auth  # noqa: F401
else:
    from .api.hive_async_api import HiveApiAsync as API  # noqa: F401
    from .api.hive_auth_async import HiveAuthAsync as Auth  # noqa: F401
from .helper.const import SMS_REQUIRED  # noqa: F401
from .hive import Hive  # noqa: F401



checking pyhiveapi version with:

> python3 -m pip list | grep hive
pyhiveapi               0.3.13

**Comment by KJonline** [comment]
@duartecordeiro ok that all looks good in your home assistant config do you have a deps folder and if you drill down can you see packages with it. There should be a site-packages folder where it all is.

**Comment by duartecordeiro** [comment]
In my .homeassistant folder, there's a deps folder, which is empty.
There's no site-packages anywhere inside any of the folders inside .homeassistant. Or am I missing something? :|

**Comment by KJonline** [comment]
@duartecordeiro can you show me what is inside the custom_components/hive/config_flow.py file?

**Comment by KJonline** [comment]
I think I spot the issue now the 2021.4.0 is only supported on home assistant 2021.4.0 or greater

**Comment by duartecordeiro** [comment]
I'll check this and feedback as soon as possible.
Thanks

**Comment by KJonline** [comment]
Did this get sorted?
