### ISSUE TITLE
HTTP status is - 504 error in log

### ISSUE THREAD

**Issue by perjury** [Pyhass/Hive-Custom-Component#84]
Seeing this error in the log occasionally

_Logger: apyhiveapi.helper.logger
Source: /usr/local/lib/python3.8/site-packages/apyhiveapi/api/hive_async_api.py:87
First occurred: 21:32:37 (1 occurrences)
Last logged: 21:32:37

Something has gone wrong calling https://beekeeper.hivehome.com/1.0/nodes/all?products=true&devices=true&actions=true - HTTP status is - 504_

All seems to work ok though

**Comment by KJonline** [comment]
Thanks for raising this I’m aware of the issue and I think I know what’s causing it.

**Comment by perjury** [comment]
Brilliant. Thanks!

**Comment by KJonline** [comment]
@perjury does this issue still occur for you? its seems to have stopped appearing in my logs, Im wondering if Hive have upgraded their servers to better handle large responses
