### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hassaan0412** [Pyhass/Hive-Custom-Component#88]
**Describe the bug**
Have installed Hive custom component via HACS. However, when go to configuration / integrations / add integrations and search for hive and then click on it to install, it tells me the 'config flow cannot be loaded' (see screenshot). The hive files are all in my custom_components folder. 

**To Reproduce**
(Have outlined above)

**Expected behaviour**
I should be able to install it

**Screenshots**

<img width="765" alt="Screenshot 2021-04-21 at 23 59 34" src="https://user-images.githubusercontent.com/82219528/115631588-06898200-a2fe-11eb-8f9a-6aa7d4dd49c3.png">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] iOS
- Browser [e.g. chrome, safari] chrome 
- Version [e.g. 22] 89.0.4389.82 

**Additional context**

**Comment by garandotorg** [comment]
Issue observed today in version 2021.5.1

**Comment by garandotorg** [comment]
@KJonline Home Assistant 2021.5.0

**Comment by KJonline** [comment]
Is this still an issue?
