### ISSUE TITLE
[BUG] climate. entity missing on home assistant 2021.5.0

### ISSUE THREAD

**Issue by peterguy04** [Pyhass/Hive-Custom-Component#91]
**Describe the bug**
i have the hive thermostat and 10x TRVs , all working great in home assistant 2021.4.6 but when i upgrade to 2021.5.0 i loose the main thermostat entities eg "climate.livingroom_trv" from every device on the integration but all other entities remain, rolling back to 2021.4.6 fixed the issue

**To Reproduce**
upgrade home assistant to latest

**Additional context**
if it matters this is running home assistant core in docker. 
switching to the official integration those entities reappear but i only get 2 entities per device (climate and battery) so 25 entities in total, rather than the 91 entities i get with the custom integration, some of which i automate from.

**Comment by dnedeltchev** [comment]
same here...

**Comment by dnedeltchev** [comment]
Right... I fixed mine. No HACS, manual install of the custom component...
I had the custom component, the hive folder, under custom_components, so I removed the integration from Integrations, removed the hive folder from custom_components, rebooted HA, added the integration without doing anything else, and now the climate.xxxxxx entries are back.

**Comment by sfgrabowski** [comment]
Thanks @dnedeltchev this fixed it for me too. Just needed to remove the hive folder in custom_components and climate entities are restored

**Comment by peterguy04** [comment]
> 
> 
> Right... I fixed mine. No HACS, manual install of the custom component...
> I had the custom component, the hive folder, under custom_components, so I removed the integration from Integrations, removed the hive folder from custom_components, rebooted HA, added the integration without doing anything else, and now the climate.xxxxxx entries are back.

@dnedeltchev so is this using the official integration now then ? do you still have the same entities as before your removed the custom integration? problem with that route for me is i loose a ton of entities and on my TRVs the state entity is important for my automations

**Comment by dnedeltchev** [comment]
> > Right... I fixed mine. No HACS, manual install of the custom component...
> > I had the custom component, the hive folder, under custom_components, so I removed the integration from Integrations, removed the hive folder from custom_components, rebooted HA, added the integration without doing anything else, and now the climate.xxxxxx entries are back.
> 
> @dnedeltchev so is this using the official integration now then ? do you still have the same entities as before you removed the custom integration? problem with that for me is i loose a ton of entities and on my TRVs the state entity is important for my automations, all i am left with is climate and battery.

@peterguy04 
Yes, the other entities are gone. I only need the climate.xxxxx entities for my automations so that works for me for now.

**Comment by dnedeltchev** [comment]
@peterguy04 
There is a 2021.5.0 custom component released. Have you tried it?

**Comment by dnedeltchev** [comment]
Spoke too soon. There is now 2021.5.1 :) @KJonline is too quick! :)

**Comment by peterguy04** [comment]
@dnedeltchev yep the latest update has fixed it :)

**Comment by KJonline** [comment]
Glad it’s sorted with the uodate
