### ISSUE TITLE
[BUG] HACS - New repository

### ISSUE THREAD

**Issue by craigmcgowan** [Pyhass/Hive-Custom-Component#94]
Since updating to 2020.5 (Home Assistant), Hive is always showing as a "New Repository" in HACS. I have been around in circles adding it (even though its already installed), deleting it, removing any reference from the .storage and readding but every time it shows as a new repository when installed.

This is the exact same issue as described https://github.com/custom-components/remote_homeassistant/issues/97

**Comment by craigmcgowan** [comment]
Further reading as this is possibly a HACS issue if the repository address for Hive has changed?
https://github.com/hacs/default/pull/757

**Comment by perjury** [comment]
I'm seeing this too

**Comment by KJonline** [comment]
Yes the hive repo name changed slightly and I have created a PR in hacs to fix this. If you search for the custom integration and install it it will still work it just HACS won’t show it as installed

**Comment by robertalexa** [comment]
Experiencing the same on 2021.5.1

On top, the entities from this don't work and I have duplicate entities for Target and Current that i suspect come from the default Hive integration that this replaces? Or i might be wrong. I have made changes to names and ids of my entities, so maybe now it got resycned and created new entities instead.

![image](https://user-images.githubusercontent.com/9019306/117587647-e7209080-b116-11eb-8ff1-4d02d77b261c.png)

**Comment by KJonline** [comment]
The PR has been merged and this issue should be fixed now
